baseURL = "https://makeroni.cc"
languageCode = "en-gb"
title = "Makeroni"
SectionPagesMenu = "main"
DefaultContentLanguage = "en"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true


[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    disable=false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  site_logo = "/images/makeroni-logo-small.png"
  show_reading_time = true
  description = "A place to meet and make online"
  mainSections= [ "news","projects","reviews" ]
  favicon = "/makeroni-logo-128x128-favicon.png"
  facebook = ""
  twitter = "https://twitter.com/makeronicc"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  discord = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  body_classes= "avenir bg-near-white"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/spencer-lbqLxgvLt0U-unsplash.jpg"
  recent_posts_number = 3